"""initial commit

Revision ID: 3981f75cd09e
Revises: 
Create Date: 2023-06-27 00:38:33.342151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3981f75cd09e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entries")
    # ### end Alembic commands ###
